from . import partner
from . import sale_order
from . import stock_picking
from . import resumen
from . import product_template
from . import account
from . import crm
from . import mail_template
from . import reply_to
from . import price_check_wizard